Fix `make prepare` to work on newer kernel
When using the tool on newer kernels (e.g., specifically on kernel
from [1] and commit e17d62fedd10ae56e2426858bd0757da544dbc73),
the `make prepare` command fails with the following:

```
...
  CC      /home/lukas/ssd/diffkemp-org/repos/bpf-next/tools/objtool/libsubcmd/exec-cmd.o
exec-cmd.c:2:10: fatal error: linux/compiler.h: No such file or directory
    2 | #include <linux/compiler.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[5]: *** [/home/lukas/ssd/diffkemp-org/repos/bpf-next/tools/build/Makefile.build:86: /home/lukas/ssd/diffkemp-org/repos/bpf-next/tools/objtool/libsubcmd/exec-cmd.o] Error 1
make[4]: *** [Makefile:78: /home/lukas/ssd/diffkemp-org/repos/bpf-next/tools/objtool/libsubcmd/libsubcmd-in.o] Error 2
make[3]: *** [Makefile:77: /home/lukas/ssd/diffkemp-org/repos/bpf-next/tools/objtool/libsubcmd/libsubcmd.a] Error 2
make[2]: *** [Makefile:73: objtool] Error 2
make[1]: *** [/home/lukas/ssd/diffkemp-org/repos/bpf-next/Makefile:1449: tools/objtool] Error 2
make: *** [Makefile:248: __sub-make] Error 2
```

Based on my search [2, 3], it looks like it could be caused
by using  `CFLAGS=-w` option. This commit replaces the option with
`KCFLAGS=-w` which fixed the problem.

[1] https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git
[2] https://www.spinics.net/lists/kernel/msg5872927.html
[3] https://stackoverflow.com/questions/79503056/how-to-pass-compiler-options-during-linux-kernel-compilation-6-13-4